spring:
  application:
    name: HealEasy
  datasource:
    url: jdbc:postgresql://localhost:5432/healEasyApp
    username: postgres
    password: 270811OLC0802023
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    baseline-on-migrate: true
  server:
    multipart:
        enabled: true
        max-file-size: 5MB
        max_request_size: 7MB
  jwt:
    accessTokenExpiration: 900
    refreshTokenExpiration: 604800
logging:
  level:
    org:
      springframework:
        security: DEBUG